#![feature(decl_macro)]
#![allow(linker_messages)]

extern crate proc_macro;

use darling::FromDeriveInput;
use proc_macro::TokenStream;
use proc_macro_error::proc_macro_error;
use quote::quote;
use syn::{DeriveInput, parse_macro_input};

/// [`format!`] but for [`syn::Ident`]
pub(crate) macro ident($($arg:tt)*) {{
    syn::Ident::new(format!($($arg)*).as_str(), proc_macro2::Span::call_site())
}}

mod args;
pub(crate) use args::Args;

mod hashing;

#[proc_macro_derive(HashStrDigest, attributes(hashstr))]
#[proc_macro_error]
pub fn derive_str_digest(ts: TokenStream) -> TokenStream {
    let input = parse_macro_input!(ts as DeriveInput);
    let receiver = hashing::HashStrDigestRec::from_derive_input(&input).unwrap();
    let tokens = quote!(#receiver);
    tokens.into()
}

mod string;

#[proc_macro_derive(HashStrWrapper, attributes(hashstr))]
#[proc_macro_error]
pub fn derive_str_wrapper(ts: TokenStream) -> TokenStream {
    let input = parse_macro_input!(ts as DeriveInput);
    let receiver = string::StrWrapperRec::from_derive_input(&input).unwrap();
    let tokens = quote!(#receiver);
    tokens.into()
}

mod tests;
use crate::tests::generate_tests;

/// Generates tests for a single hash str type.
///
/// Tests can be selectively omitted using `ignore_tests`:
/// ```rust,ignore
/// impl_hashstr_tests!(
///     hasher = Sha1,
///     hash_name = "Sha1Checked",
///     con = U20,
///     ignore_tests = ["digest"]
/// );
/// ```
#[proc_macro]
#[proc_macro_error]
pub fn impl_hashstr_tests(input: TokenStream) -> TokenStream {
    tests::impl_hashstr_tests(input)
}

mod implementor;

#[proc_macro]
#[proc_macro_error]
/// Generates impls for the simplest of hashers that don't require anything special
///
/// This is the full suite. Lower and uppercase variants and assotiated tests are all generated by
/// this.
pub fn impl_hashstr(input: TokenStream) -> TokenStream {
    implementor::impl_hashstr(input)
}
