# https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "hashstr-derive"
description = "Derive macro magic behind the hashstr crate"
version = "0.2.0"
edition = "2024"
authors = ["Zentheon <zentheon@mailbox.org>"]
readme = "./README.md"
license = "LGPL-3.0-or-later"
license-file = "./LICENSE"
repository = "https://github.com/Zentheon/hashstr"
homepage = "https://github.com/Zentheon/hashstr"

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
syn = { version = "2.0", features = ["full"] }
proc-macro2 = "1.0"
darling = "0.23.0"
proc-macro-error = "1.0.4"
