# https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
authors = ["Zentheon <zentheon@mailbox.org>"]
edition = "2024"
name = "sha3-strings"
description = "Convenient string-like types that wrap the `sha3` crate"
version = "0.1.0"
readme = "../README.md"
repository = "https://github.com/Zentheon/hash-strings"
homepage = "https://github.com/Zentheon/hash-strings"
license-file = "../LICENSE"

[features]
default = ["tracing"]
tracing = ["dep:tracing"]

[dependencies]
hash-strings = { version = "0.1.0", path = "../hash-strings" }
hash-strings-derive = { path = "../hash-strings-derive" }
serde = { version = "1.0.219" }
tracing = { version = "0.1.41", optional = true }
digest = "0.11.2"
digest-io = "0.1.0"
base16ct = { version = "1.0.0", features = ["alloc"] }
sha3 = "0.11.0"
