name: Build, test and publish release

# TODO: Figure out how to IO built binaries.

# This workflow contains three jobs, each a dependent of the next:
# build-and-test:
#   Build and test packages, generate SBOMs and upload relevant artifacts
#
# crates-io-release:
#   Publish the release to crates.io
#
# github-release:
#   Retrieves the `release-artifacts` from `build-and-test`, attests and creates a release with those files

on:
  push:
    tags: [ '[0-9]+.[0-9]+.[0-9]+' ]

jobs:
  build-and-test:
      name: Build + test, generate and check SBOM
      runs-on: ubuntu-latest
      environment: release
      defaults:
        run:
          shell: devenv shell bash -- -e {0}

      steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: Setup Cachix
        uses: cachix/cachix-action@v16
        with:
          name: devenv

      - name: Install devenv.sh
        shell: bash
        run: nix profile add nixpkgs#devenv

      - name: Run tests
        run: cargo test --verbose --all-features

      - name: Create package for attestation
        run: cargo package --all-features

      - name: Generate SBOMs
        run: cargo cyclonedx --all-features -f xml && cargo cyclonedx --all-features -f json

      - name: Scan SBOMs
        uses: anchore/scan-action@v7
        with:
          # https://github.com/anchore/scan-action/issues/673
          sbom: ${{ github.workspace }}/hashstr/hashstr.cdx.json

      - name: Upload artifacts for Github release
        uses: actions/upload-artifact@v3
        with:
          name: release-artifacts
          retention-days: 1
          if-no-files-found: error
          path: |
            ${{ github.workspace }}/target/package/*.crate
            ${{ github.workspace }}/CHANGELOG.md
            ${{ github.workspace }}/*/*.cdx.xml
            ${{ github.workspace }}/*/*.cdx.json

  crates-io-release:
    name: Create crates.io release
    needs: build-and-test
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    defaults:
      run:
        shell: devenv shell bash -- -e {0}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v6

    - name: Install Nix
      uses: cachix/install-nix-action@v31

    - name: Setup Cachix
      uses: cachix/cachix-action@v16
      with:
        name: devenv

    - name: Install devenv.sh
      shell: bash
      run: nix profile add nixpkgs#devenv

    - name: Obtain trusted publishing key
      id: auth
      uses: rust-lang/crates-io-auth-action@v1

    - name: Publish release to crates.io
      # remove the -n flag if nothing explodes
      run: cargo publish -n
      env:
        CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}

  github-release:
    name: Create Github release
    needs: crates-io-release
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Retrieve artifacts
        uses: actions/download-artifact@v7
        with:
          path: ${{ github.workspace }}/release-artifacts
          name: release-artifacts

      - name: Extract changelog to body file
        run: |
          awk '/^## ${{ github.ref_name }} -/ {flag=1; next} /^- - -/ {flag=0} flag' CHANGELOG.md > ${{ github.workspace }}/release_body.md

      - name: Attest release
        id: attest
        uses: actions/attest@v4
        with:
          subject-path: ${{ github.workspace }}/release-artifacts/*.crate
          sbom-path: ${{ github.workspace }}/release-artifacts/*.cdx.json

      - name: Create release
        uses: softprops/action-gh-release@v7
        with:
          draft: true # remove this line if nothing explodes
          body_path: ${{ github.workspace }}/release_body.md
          files: |
            ${{ steps.attest.outputs.bundle-path }}
            ${{ github.workspace }}/release-artifacts/CHANGELOG.md
            ${{ github.workspace }}/release-artifacts/*/*.cdx.xml
            ${{ github.workspace }}/release-artifacts/*/*.cdx.json
